import { useState } from 'react';
import { Calendar, Sparkles, Download, MapPin, ArrowRight, CheckCircle2 } from 'lucide-react';
import DigitalPathwaysMap from './DigitalPathwaysMap';

export default function TripPlanner() {
  const [daysInput, setDaysInput] = useState(5);
  const [style, setStyle] = useState('Heritage & Nature');
  const [activeDay, setActiveDay] = useState(1);

  const basePool = [
    { location: "Kandy Sacred City", title: "Kandy Temple of Tooth & Botanical Gardens", desc: "Arrive at Kandy, visit Royal Botanical Gardens, Temple of Sacred Tooth Relic, and traditional Kandyan dance." },
    { location: "Sigiriya Citadel", title: "Sigiriya Fortress & Minneriya Safari", desc: "Climb 5th-century Sigiriya Rock Fortress at sunrise, afternoon wild elephant safari at Minneriya." },
    { location: "Ella Mountain Valley", title: "Nine Arches Bridge & Little Adam's Peak", desc: "Take iconic train trip to Ella, hike Little Adam's Peak for sunrise, visit Nine Arches Bridge." },
    { location: "Galle Dutch Fort", title: "Galle 17th-Century Colonial Fort", desc: "Explore UNESCO fort lighthouse, cobblestone boutique streets, and ocean view ramparts." },
    { location: "Jaffna Peninsula", title: "Jaffna Tamil Cultural Heritage", desc: "Visit Nallur Kandaswamy Kovil, Jaffna Dutch Fort, and try traditional Jaffna crab curry." },
    { location: "Mirissa Palm Beach", title: "Mirissa Beach & Whale Watching", desc: "Golden palm beach sunset, morning blue whale watching cruise in deep ocean." },
    { location: "Trincomalee Coast", title: "Trincomalee Nilaveli & Pigeon Island", desc: "Snorkeling at Pigeon Island national park, Koneswaram temple on Swami Rock cliff." }
  ];

  const totalDays = Math.max(1, Math.min(14, Number(daysInput) || 1));

  const generatedDaysPlan = Array.from({ length: totalDays }, (_, idx) => {
    const poolItem = basePool[idx % basePool.length];
    return {
      day: idx + 1,
      location: poolItem.location,
      title: `Day ${idx + 1}: ${poolItem.title}`,
      desc: poolItem.desc
    };
  });

  const handleDownload = () => {
    const textContent = `=========================================
SRI LANKA TAILORED TRAVEL ITINERARY (${totalDays} DAYS)
Style: ${style}
=========================================\n\n` +
      generatedDaysPlan.map(d => `DAY ${d.day} - ${d.location.toUpperCase()}\nActivity: ${d.title}\nDetails: ${d.desc}\n\n`).join('') +
      `-----------------------------------------\nGenerated by VisitCeylon AI Trip Planner`;

    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Sri_Lanka_${totalDays}_Day_Itinerary.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div id="trip-planner" className="w-full bg-slate-950 py-20 px-6 text-white border-t border-slate-800 relative overflow-hidden">
      <div className="max-w-7xl mx-auto">
        
        {/* Section Header without icon */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-10 gap-4">
          <div>
            <h2 className="text-4xl md:text-5xl font-editorial font-extrabold text-white mb-3">
              Interactive Custom Itinerary Generator
            </h2>
            <p className="text-gray-400 text-base md:text-lg max-w-2xl font-medium">
              Enter your exact trip duration in days and choose your travel style to generate a custom itinerary.
            </p>
          </div>
        </div>

        {/* Builder Form Controls */}
        <div className="bg-slate-900 border border-slate-800 p-6 md:p-8 rounded-3xl shadow-2xl mb-12 grid grid-cols-1 md:grid-cols-3 gap-6 items-center">
          
          {/* Custom Days Input */}
          <div>
            <label className="block text-xs font-extrabold text-emerald-400 uppercase mb-3 flex items-center gap-2 tracking-wider">
              <Calendar size={16} className="text-emerald-400" /> Enter Trip Duration (Days)
            </label>
            <div className="flex items-center gap-3 bg-slate-800 border border-slate-700 rounded-2xl px-4 py-2">
              <input
                type="number"
                min="1"
                max="14"
                value={daysInput}
                onChange={(e) => {
                  setDaysInput(e.target.value);
                  setActiveDay(1);
                }}
                className="w-full bg-transparent text-white font-extrabold text-lg focus:outline-none"
                placeholder="e.g. 10"
              />
              <span className="text-xs font-extrabold text-emerald-400 whitespace-nowrap bg-emerald-950 px-3 py-1 rounded-xl border border-emerald-800">
                Days
              </span>
            </div>
          </div>

          {/* Travel Style Selection */}
          <div>
            <label className="block text-xs font-extrabold text-emerald-400 uppercase mb-3 flex items-center gap-2 tracking-wider">
              <Sparkles size={16} className="text-emerald-400" /> Travel Preference
            </label>
            <select
              value={style}
              onChange={(e) => setStyle(e.target.value)}
              className="w-full bg-slate-800 border border-slate-700 rounded-2xl px-4 py-3 text-sm font-extrabold text-white focus:outline-none focus:border-emerald-500 cursor-pointer"
            >
              <option value="Heritage & Nature">🏛️ Heritage, Nature & Tea Trails</option>
              <option value="Wildlife Safari">🐘 Wildlife Safaris & Jungle Trek</option>
              <option value="Beach & Surfing">🏄 Coastal Beaches & Surfing</option>
            </select>
          </div>

          {/* Action Button */}
          <div className="md:pt-7">
            <button
              onClick={() => setActiveDay(1)}
              className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-extrabold py-3.5 px-6 rounded-2xl transition-all shadow-xl flex items-center justify-center gap-2 text-base cursor-pointer border border-emerald-400/40"
            >
              <Sparkles size={18} /> Generate Custom Plan
            </button>
          </div>

        </div>

        {/* 3D Digital Pathways Map & Details Section */}
        <div className="bg-slate-900/90 border border-slate-800 p-8 md:p-12 rounded-3xl shadow-2xl relative">
          
          <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-6 mb-8 border-b border-slate-800 gap-4">
            <div>
              <span className="text-xs text-emerald-400 font-extrabold uppercase tracking-widest bg-emerald-500/10 px-3 py-1 rounded-full border border-emerald-500/20">
                Custom Plan Ready ({totalDays} Days)
              </span>
              <h3 className="text-3xl md:text-4xl font-editorial font-extrabold text-white mt-2">
                {totalDays}-Day Tailored Sri Lanka Itinerary
              </h3>
            </div>
            <button
              onClick={handleDownload}
              className="flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-500 text-white font-extrabold text-xs px-5 py-3 rounded-xl transition-all shadow-lg cursor-pointer"
            >
              <Download size={16} /> Save / Download Plan
            </button>
          </div>

          {/* 3D Digital Pathways Map Graphic (Matching Screenshot 4) */}
          <div className="mb-10">
            <DigitalPathwaysMap 
              daysPlan={generatedDaysPlan} 
              activeDay={activeDay}
              onSelectDay={(dayNum) => setActiveDay(dayNum)}
            />
          </div>

          {/* Expanded Details Card */}
          <div className="bg-slate-950 border border-slate-800 p-8 rounded-3xl shadow-2xl relative">
            {(() => {
              const activeItem = generatedDaysPlan.find(d => d.day === activeDay) || generatedDaysPlan[0];
              return (
                <div className="space-y-6">
                  <div className="flex items-center justify-between">
                    <span className="bg-emerald-500/20 text-emerald-400 font-extrabold text-xs px-3 py-1 rounded-full border border-emerald-500/30">
                      Day {activeItem.day} of {totalDays}
                    </span>
                    <span className="text-slate-400 text-xs font-bold flex items-center gap-1">
                      <MapPin size={14} className="text-emerald-400" /> {activeItem.location}
                    </span>
                  </div>

                  <h4 className="text-2xl md:text-3xl font-editorial font-extrabold text-white leading-tight">
                    {activeItem.title}
                  </h4>

                  <p className="text-gray-300 text-base leading-relaxed font-medium bg-slate-900/80 p-5 rounded-2xl border border-slate-800">
                    {activeItem.desc}
                  </p>

                  <div className="pt-2 flex items-center justify-between">
                    <div className="flex items-center gap-2 text-xs font-extrabold text-emerald-400">
                      <Sparkles size={16} /> SLTDA Verified Route
                    </div>

                    {activeDay < generatedDaysPlan.length && (
                      <button 
                        onClick={() => setActiveDay(prev => prev + 1)}
                        className="inline-flex items-center gap-2 text-xs font-extrabold text-white bg-emerald-600 hover:bg-emerald-500 px-4 py-2 rounded-xl transition-all cursor-pointer"
                      >
                        Next Day <ArrowRight size={14} />
                      </button>
                    )}
                  </div>
                </div>
              );
            })()}
          </div>

        </div>

      </div>
    </div>
  );
}